### ISSUE TITLE
Adding a Test Issue from Trello

### ISSUE THREAD

**Issue by BethanyG** [alpaca-lib/alpaca#49]
Hi Omar,

So....this *appears* to have stabilized...I left GitHub and Trello open all night, and there were no loops.  So...the only other thing to test is having you log in and make some changes and see if *that* triggers recursion....I sincerely hope not, because this was NOT the point of the project!

**Comment by osanseviero** [comment]
Hey :) Which is the trello board? (I see that you removed me from the previous one)

**Comment by BethanyG** [comment]
Sent you a link to join in your gmail.  Apologies! (don't want to attach it here, as this is public.)

**Comment by osanseviero** [comment]
Don't worry. Thank you!

**Comment by osanseviero** [comment]
Thanks for fixing this!
